name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Create a Tag
        run: |
          # Create a new tag
          VERSION=$(node -p "require('./package.json').version")
          git config --local user.name "Cedric0303"
          git config --local user.email "chenjunli7@gmail.com"
          git tag -a "v$VERSION" -m "Release $VERSION"
          git push origin "v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
